### ISSUE TITLE
Extract AcmeDnsClient and Storage classes to their own files

### ISSUE THREAD

**Issue by Yannik** [joohoi/acme-dns-certbot#1]
Hey,
thanks for this. It would be great if AcmeDnsClient and Storage would be extracted to their own files, so we can independently use them in hooks for other letsencrypt clients. (I for one don't use certbot, but would like to migrate my hook to your AcmeDnsClient implementation)

**Comment by Yannik** [comment]
Maybe it makes sense to even move them to a acme-dns-python-lib repository and just submodule that here (or provide appropriate installation instructions)

**Comment by joohoi** [comment]
I wish to keep it this way for ease of installation and in order to not to clutter the filesystem.

That said, the code itself should be 99% client agnostic. The only values that you'd need to change, would be the ones in the very top of the file, that currently pick the domain and challenge token from the environment variables.

**Comment by Yannik** [comment]
I thought that was your reasoning here. However, it would be very useful to be able to just drop these 2 classfiles into your own hook project and be able to (whenever it arises in the future) just replace these with newer versions, instead of carefully merging. (After all, it doesn't really matter whether you `git clone` a repo with three files (right now) or five. And that probably is the way most letsencrypt clients get installed anyway)

**Comment by joohoi** [comment]
Ah, totally. I'll fork them to an external project in the coming days. Will be pushing to PyPI too if you see that'd be useful.

**Comment by Yannik** [comment]
Yeah, I definitely thought about pushing them to pypi as well. That would be great. This way, the acme-dns-certbot installation instructions can simply be modified by one additional `pip install` step and it is still just one python file in this project.

**Comment by joohoi** [comment]
This is now a thing. It's available on PyPI: [https://pypi.python.org/pypi/pyacmedns/](https://pypi.python.org/pypi/pyacmedns/) and the code is hosted at [https://github.com/joohoi/pyacmedns](https://github.com/joohoi/pyacmedns)
