### ISSUE TITLE
Question: usage in cron

### ISSUE THREAD

**Issue by pscheit** [joohoi/acme-dns-certbot#11]
Hey there!

thanks for providing acme-dns, I used and loved it so far.

One Question is left (from the readme): How would i call the manual auth hook in my cron script? Afaik I cannot use --manual as method in certbot renew.
Would I call certonly without --debug-challenges all the time? So no `renew`? command?

Thanks in advance

**Comment by joohoi** [comment]
Hi, and thanks! It’s nice to hear that it has been able to help you!

The manual auth hook path as well as other settings are saved to Certbots
renewal configuration file that’s read upon calling certbot renew from cron
script. —manual accompanied with a hook runs perfectly fine in renew! You
should be fine with default renew cron job after just running it initially
with the example command line. —debug-challenges is a oneshot option, and
it doesn’t interfere with the non interactive renew call.

**Comment by pscheit** [comment]
thanks, it works like a charm. If one supplies the manual-auth-hook he can use manual as a method for non interactive use in renew.
thank you!
