### ISSUE TITLE
How do I automatically reload Apache after renewal

### ISSUE THREAD

**Issue by saudiqbal** [joohoi/acme-dns-certbot#15]
I saw the a new certificate got issued on renewal but was not showing up online, I reloaded Apache and there it was. Is it possible to reload apache after successful cert renewal?

**Comment by joohoi** [comment]
Sure! There's a few options to do this: 
 - You can use Certbot's Apache plugin to install the certificate, which makes Certbot to automatically restart Apache when certificate is renewed.
 - You can create a custom script that restarts Apache (or other services) when the certificate is renewed. Make the script executable, and place it to `/etc/letsencrypt/renewal-hooks/deploy` and it gets run when a certificate on your system gets renewed.

**Comment by theel0ja** [comment]
`certbot renew --deploy-hook "systemctl reload apache2"` (you may need to change the command in case you are not using Debian/Ubuntu)

**Comment by Vector-Green** [comment]
what if I'm using docker)))
where everything is in separate container)))
