### ISSUE TITLE
make `_acme-challenge.` subdomain configurable

### ISSUE THREAD

**Issue by jvanasco** [joohoi/acme-dns-certbot#2]
I think this is the relevant place to post this...

Some DNS systems, such as the ones people would use acme-dns instead of, don't allow a leading underscore in CNAME records.

why? a leading underscore is prohibited in hostnames, but allowed in other dns records. Some systems are trying to safeguard users, others are confused in implementations, and others... who knows.

anways, `_acme-challenge.` is hardcoded here:

https://github.com/joohoi/acme-dns-certbot/blob/1873fd105a72544173a3461237dcc1974a06bbb5/acme-dns-auth.py#L25

I believe you can supply an alternate.  there's a bit of a discussion here https://community.letsencrypt.org/t/acme-sh-support-domain-alias-mode-now/52700/5

**Comment by joohoi** [comment]
The hardcoded value is only used for printing the user instructions [here](https://github.com/joohoi/acme-dns-certbot/blob/1873fd105a72544173a3461237dcc1974a06bbb5/acme-dns-auth.py#L150). 

The main issue is that in this case these DNS providers do not allow Let's Encrypt DNS challenges at all. That's because Let's encrypt will always ask for the `_acme-challenge.domain-to-be-validated.tld` record, and this cannot be changed on the client side.

**Comment by joohoi** [comment]
Oh, to clarify: the `_acme-challenge` goes to the CNAME record name, as this is the record that Let's Encrypt is checking. Acme-dns generated subdomains do not have this prefix at all, so you won't be creating a CNAME _to_ a hostname starting with an underscore.

**Comment by jvanasco** [comment]
Ok, then this shouldn't be an issue with most "bad" DNS hosts.

The issue was with other libraries that originally required the cname to be onto an "_acme-challenge" prefix.

I believe the underscore is usually valid for the key but not the value in the cname record on the providers I found.

**Comment by joohoi** [comment]
Awesome! Hope you can work with this information. I'm going to close this issue for now, but please comment here if needed, and I'll reopen.

**Comment by jvanasco** [comment]
Thanks for the quick replies! I haven't even dug into using this package yet, a quick glance suggested it had the same limitation as another system (which required the CNAME to be set up a special way). Looking deeper at the acme-dns package, it doesn't have that limitation at all.
