### ISSUE TITLE
Pre-Hook Key Error: CERTBOT_DOMAIN

### ISSUE THREAD

**Issue by cwchristerw** [joohoi/acme-dns-certbot#28]
Running pre-hook command: /etc/letsencrypt/renewal-hooks/pre/acme-dns-auth.py
Hook 'pre-hook' reported error code 1
Hook 'pre-hook' ran with error output:
 Traceback (most recent call last):
   File "/etc/letsencrypt/renewal-hooks/pre/acme-dns-auth.py", line 22, in <module>
     DOMAIN = os.environ["CERTBOT_DOMAIN"]
   File "/usr/local/lib/python3.10/os.py", line 680, in __getitem__
     raise KeyError(key) from None
 KeyError: 'CERTBOT_DOMAIN

**Comment by cwchristerw** [comment]
I'm not sure what may cause this error because python script works properly even with this error.

**Comment by maddes-b** [comment]
The script is an manual-auth-hook, not a pre-hook.
It should be located in /usr/local/bin or similar and used as a manual-auth-hook.

I wrote my own acme-dns-client that works with certbot and acme.sh.
Please have a look here: https://github.com/maddes-b/acme-dns-client-2
Feedback welcome.

**Comment by cwchristerw** [comment]
I'm aware of that its manual-auth-hook script and in command `--manual-auth-hook /etc/letsencrypt/renewal-hooks/pre/acme-dns-auth.py`. I have just placed in /renewal-hooks/pre/ directory because there were no predefined directory for auth-hooks.

**Comment by maddes-b** [comment]
Some keep it in `/etc/letsencrypt` directly. So it is separate but still inside the letsencrypt directory. Just personal preference.
