### ISSUE TITLE
Missing . in CNAME instructions.

### ISSUE THREAD

**Issue by nielsbasjes** [joohoi/acme-dns-certbot#3]
I have an experimental setup of acme-dns under auth.basjes.nl
When I run this against a different domain I own I see this:

```
Output from acme-dns-auth.py:
Please add the following CNAME record to your main DNS zone:
_acme-challenge.somedomain.nl CNAME 963ab1da-54bc-4301-9f89-d1393729e78e.auth.basjes.nl
```

The subtle problem is that if I do it exactly as instructed a dns lookup for 
`_acme-challenge.somedomain.nl` 
results in 
`963ab1da-54bc-4301-9f89-d1393729e78e.auth.basjes.nl.somedomain.nl`

The problem lies in the fact that because the '.' is missing in the CNAME dns assumes it is a subdomain of the current zone.
The simple fix for this is to add a '.' in the instructions.

**Comment by joohoi** [comment]
Nice catch and a quick fix, thank you!
